[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "RealESRGAN"
version = "1.0"
dependencies = { file = ["requirements.txt"] }

[tool.setuptools]
packages = ["RealESRGAN"]

